// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using firstRest.Data;

#nullable disable

namespace firstRest.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250402233816_Add_Students_With_Json_Seed")]
    partial class Add_Students_With_Json_Seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("firstRest.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<decimal>("Grade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("36cb9cd5-6005-406e-b08f-84c7525393b3"),
                            Age = 23,
                            Grade = 87.88m,
                            Name = "Ali Saeed"
                        },
                        new
                        {
                            Id = new Guid("6c1a8f5a-b390-4131-ba25-40f517fbeedd"),
                            Age = 20,
                            Grade = 77.05m,
                            Name = "Sara Nasser"
                        },
                        new
                        {
                            Id = new Guid("7d5a0874-cd49-4e46-8c07-a3d6c397f4f6"),
                            Age = 23,
                            Grade = 72.72m,
                            Name = "Hassan Saeed"
                        },
                        new
                        {
                            Id = new Guid("fd3fb50a-0788-474c-8f41-e641247178d6"),
                            Age = 21,
                            Grade = 92.74m,
                            Name = "Mona Salem"
                        },
                        new
                        {
                            Id = new Guid("453527e2-2458-46a0-b197-c13dc524e31c"),
                            Age = 24,
                            Grade = 59.99m,
                            Name = "Hassan Salem"
                        },
                        new
                        {
                            Id = new Guid("917c3785-6f98-4617-a5db-36f8588275db"),
                            Age = 19,
                            Grade = 52.39m,
                            Name = "Hassan Nasser"
                        },
                        new
                        {
                            Id = new Guid("19c2e364-7b57-4768-9a59-3bcf3601c921"),
                            Age = 25,
                            Grade = 90.42m,
                            Name = "Hassan Fahmy"
                        },
                        new
                        {
                            Id = new Guid("ad075ccf-04cd-4d55-b990-a05389f60963"),
                            Age = 20,
                            Grade = 63.71m,
                            Name = "Noor Nasser"
                        },
                        new
                        {
                            Id = new Guid("51e5342f-b275-481d-a15b-216cb27b1c48"),
                            Age = 23,
                            Grade = 65.81m,
                            Name = "Khaled Tawfik"
                        },
                        new
                        {
                            Id = new Guid("91a9c206-849b-4320-94ae-d8f47266cbde"),
                            Age = 21,
                            Grade = 94.89m,
                            Name = "Noor Salem"
                        },
                        new
                        {
                            Id = new Guid("edd4d812-9fdd-4264-8262-70da7721a89a"),
                            Age = 21,
                            Grade = 80.67m,
                            Name = "Laila Tawfik"
                        },
                        new
                        {
                            Id = new Guid("2fdfb4c7-1742-47cf-bd52-7d6ba9aa03cb"),
                            Age = 20,
                            Grade = 76.69m,
                            Name = "Ahmed Mohamed"
                        },
                        new
                        {
                            Id = new Guid("1a560fb3-a2fc-41a8-bd0f-28aa4f6e1e2d"),
                            Age = 22,
                            Grade = 53.46m,
                            Name = "Omar Ismail"
                        },
                        new
                        {
                            Id = new Guid("c3fccf6c-ded9-43a1-8eae-b55078c7a22f"),
                            Age = 25,
                            Grade = 83.26m,
                            Name = "Khaled Gad"
                        },
                        new
                        {
                            Id = new Guid("b1e83397-63ae-4802-acb7-a3d3da9af5bb"),
                            Age = 21,
                            Grade = 77.3m,
                            Name = "Ahmed Ibrahim"
                        },
                        new
                        {
                            Id = new Guid("b4d202e5-bf02-4ea6-a0ec-f4846f1cec6f"),
                            Age = 20,
                            Grade = 50.11m,
                            Name = "Khaled Hussein"
                        },
                        new
                        {
                            Id = new Guid("ca950405-494a-481e-952d-e81057ab53eb"),
                            Age = 20,
                            Grade = 75.49m,
                            Name = "Ali Ismail"
                        },
                        new
                        {
                            Id = new Guid("34be3919-3635-434b-91d5-b7da059842d7"),
                            Age = 24,
                            Grade = 62.14m,
                            Name = "Khaled Gad"
                        },
                        new
                        {
                            Id = new Guid("ee840c60-136d-4e4f-b8a1-d75046fadd3d"),
                            Age = 25,
                            Grade = 78.83m,
                            Name = "Laila Ismail"
                        },
                        new
                        {
                            Id = new Guid("e3a9bd8a-2464-4e3a-bf59-9b39a19de3f5"),
                            Age = 25,
                            Grade = 78.46m,
                            Name = "Ahmed Nasser"
                        },
                        new
                        {
                            Id = new Guid("8be8a216-7e27-45b6-bbac-9dccc6625698"),
                            Age = 20,
                            Grade = 86.4m,
                            Name = "Ali Ibrahim"
                        },
                        new
                        {
                            Id = new Guid("b227543c-1553-4e55-a5c1-1cff5197d127"),
                            Age = 25,
                            Grade = 95.14m,
                            Name = "Youssef Hussein"
                        },
                        new
                        {
                            Id = new Guid("39217bba-eabf-4508-a9b2-b0ac3c53fa0c"),
                            Age = 25,
                            Grade = 84.45m,
                            Name = "Sara Saeed"
                        },
                        new
                        {
                            Id = new Guid("2942a691-c02d-4762-9107-e6b06e614441"),
                            Age = 25,
                            Grade = 87.95m,
                            Name = "Omar Hussein"
                        },
                        new
                        {
                            Id = new Guid("055d3426-5a06-4308-8134-ac1bc4d8055f"),
                            Age = 21,
                            Grade = 84.28m,
                            Name = "Khaled Ibrahim"
                        },
                        new
                        {
                            Id = new Guid("0ea8126e-2c60-4cc8-898c-e8dfdf15c153"),
                            Age = 23,
                            Grade = 91.16m,
                            Name = "Omar Hussein"
                        },
                        new
                        {
                            Id = new Guid("141e5358-f415-47cf-9ab8-364fe71e7f77"),
                            Age = 24,
                            Grade = 64.37m,
                            Name = "Laila Ibrahim"
                        },
                        new
                        {
                            Id = new Guid("de43f780-49ed-4be9-a0e7-359c9ce4afde"),
                            Age = 19,
                            Grade = 93.56m,
                            Name = "Omar Tawfik"
                        },
                        new
                        {
                            Id = new Guid("0e1a3ad2-5aed-442d-849a-4c9be5e3e8f3"),
                            Age = 25,
                            Grade = 84.84m,
                            Name = "Omar Ibrahim"
                        },
                        new
                        {
                            Id = new Guid("3947251c-fa71-40b8-a7ec-bdf2f7513219"),
                            Age = 19,
                            Grade = 50.33m,
                            Name = "Youssef Ismail"
                        },
                        new
                        {
                            Id = new Guid("41039cea-5299-4a7e-93ef-e175025de39d"),
                            Age = 20,
                            Grade = 50.34m,
                            Name = "Noor Hussein"
                        },
                        new
                        {
                            Id = new Guid("ef46f0cc-ca70-4972-bf8d-6277a0b6314e"),
                            Age = 20,
                            Grade = 90.14m,
                            Name = "Khaled Nasser"
                        },
                        new
                        {
                            Id = new Guid("42cf7a61-b692-4213-9a7b-66ffe1bcb3eb"),
                            Age = 21,
                            Grade = 58.32m,
                            Name = "Ali Ibrahim"
                        },
                        new
                        {
                            Id = new Guid("823aac75-3a1f-4164-ba45-0c4e6e3523c8"),
                            Age = 24,
                            Grade = 78.52m,
                            Name = "Omar Saeed"
                        },
                        new
                        {
                            Id = new Guid("10317f7e-9cee-4ceb-9071-e04ecfc1b5a1"),
                            Age = 22,
                            Grade = 76.72m,
                            Name = "Sara Gad"
                        },
                        new
                        {
                            Id = new Guid("d50c7cf1-6c98-4287-abb5-27b12ed559a6"),
                            Age = 20,
                            Grade = 70.23m,
                            Name = "Khaled Ismail"
                        },
                        new
                        {
                            Id = new Guid("03bb102d-88bd-46d5-adad-1b1dc2c521d9"),
                            Age = 18,
                            Grade = 54.4m,
                            Name = "Laila Salem"
                        },
                        new
                        {
                            Id = new Guid("f9ce4fcd-a86f-4907-ae1f-92e29cc69a42"),
                            Age = 20,
                            Grade = 86.41m,
                            Name = "Laila Ismail"
                        },
                        new
                        {
                            Id = new Guid("f255e278-88b8-4d02-9f45-b8bad00afc28"),
                            Age = 23,
                            Grade = 74.96m,
                            Name = "Mona Gad"
                        },
                        new
                        {
                            Id = new Guid("c9c91b70-b626-4a40-8d50-d0564ce82b5f"),
                            Age = 19,
                            Grade = 97.71m,
                            Name = "Sara Ismail"
                        },
                        new
                        {
                            Id = new Guid("c095f959-5bae-43da-af24-407333af6424"),
                            Age = 19,
                            Grade = 90.24m,
                            Name = "Noor Ismail"
                        },
                        new
                        {
                            Id = new Guid("c9e4eeda-acfb-46cf-b4fa-a18583dd36d7"),
                            Age = 23,
                            Grade = 82.59m,
                            Name = "Mona Hussein"
                        },
                        new
                        {
                            Id = new Guid("99cdde86-9a44-40e2-b9ab-9f0f4742edc3"),
                            Age = 25,
                            Grade = 80.95m,
                            Name = "Mona Hussein"
                        },
                        new
                        {
                            Id = new Guid("62d47d1c-03c5-4bf8-95f5-e17849360f00"),
                            Age = 21,
                            Grade = 94.81m,
                            Name = "Sara Hussein"
                        },
                        new
                        {
                            Id = new Guid("34ef0afe-729d-4d68-9535-6605b51e1db7"),
                            Age = 23,
                            Grade = 83.14m,
                            Name = "Sara Fahmy"
                        },
                        new
                        {
                            Id = new Guid("4f6f0dff-e472-42d1-a43c-e367829944eb"),
                            Age = 23,
                            Grade = 66.88m,
                            Name = "Ahmed Mohamed"
                        },
                        new
                        {
                            Id = new Guid("45d48c42-d1c3-4b68-ba23-ab90868292fc"),
                            Age = 23,
                            Grade = 73.27m,
                            Name = "Laila Hussein"
                        },
                        new
                        {
                            Id = new Guid("b13a80db-01ea-49f4-8a18-b194a1aa0510"),
                            Age = 21,
                            Grade = 72.33m,
                            Name = "Laila Saeed"
                        },
                        new
                        {
                            Id = new Guid("7f9c5598-545b-450e-abb5-3104e5caabf3"),
                            Age = 22,
                            Grade = 85.51m,
                            Name = "Youssef Salem"
                        },
                        new
                        {
                            Id = new Guid("dd3b6cbc-0e2d-405b-a2b6-2aec1113cb0b"),
                            Age = 18,
                            Grade = 62.24m,
                            Name = "Mona Nasser"
                        },
                        new
                        {
                            Id = new Guid("94e6a95b-1dcb-43ca-9542-f0c0f4be1c78"),
                            Age = 25,
                            Grade = 89.51m,
                            Name = "Mona Ibrahim"
                        },
                        new
                        {
                            Id = new Guid("91b2347f-7a74-4e76-8965-5d56dcb5b5c8"),
                            Age = 22,
                            Grade = 70.77m,
                            Name = "Laila Tawfik"
                        },
                        new
                        {
                            Id = new Guid("4b6ef335-0fd5-4ec9-bbf8-020943b12517"),
                            Age = 19,
                            Grade = 65.97m,
                            Name = "Khaled Hussein"
                        },
                        new
                        {
                            Id = new Guid("fb40aeaf-2b33-47b7-aa2d-60e67a4ebeac"),
                            Age = 23,
                            Grade = 71.08m,
                            Name = "Ali Ismail"
                        },
                        new
                        {
                            Id = new Guid("784f7ef8-e8c7-4714-ba2b-cbde020a6de5"),
                            Age = 23,
                            Grade = 95.15m,
                            Name = "Omar Salem"
                        },
                        new
                        {
                            Id = new Guid("1537c84e-240c-4677-9f1e-8c779d31c8c7"),
                            Age = 25,
                            Grade = 71.04m,
                            Name = "Ahmed Saeed"
                        },
                        new
                        {
                            Id = new Guid("0ecb042b-36f4-4a8b-a1be-c4a2505ef53f"),
                            Age = 23,
                            Grade = 81.63m,
                            Name = "Omar Saeed"
                        },
                        new
                        {
                            Id = new Guid("9f063552-5459-4a2c-8cf8-1bb7453d7c55"),
                            Age = 19,
                            Grade = 59.87m,
                            Name = "Laila Ibrahim"
                        },
                        new
                        {
                            Id = new Guid("ed5cfda8-e925-4c08-82d7-18f39a5acc4d"),
                            Age = 20,
                            Grade = 71.06m,
                            Name = "Ali Fahmy"
                        },
                        new
                        {
                            Id = new Guid("c1ae59ed-d4fe-44ae-98f6-96f998f42809"),
                            Age = 20,
                            Grade = 93.01m,
                            Name = "Mona Ismail"
                        },
                        new
                        {
                            Id = new Guid("add3d76d-4359-46d9-b453-abddfeb04909"),
                            Age = 21,
                            Grade = 74.6m,
                            Name = "Ahmed Mohamed"
                        },
                        new
                        {
                            Id = new Guid("72d2df13-c26f-4fff-8e61-5177de29f2bb"),
                            Age = 23,
                            Grade = 64.37m,
                            Name = "Omar Ibrahim"
                        },
                        new
                        {
                            Id = new Guid("703e5f7c-d560-4893-8e06-29ea95884c48"),
                            Age = 19,
                            Grade = 77.94m,
                            Name = "Khaled Fahmy"
                        },
                        new
                        {
                            Id = new Guid("c15059a3-0666-4ee7-abc5-93145e8ce261"),
                            Age = 24,
                            Grade = 78.59m,
                            Name = "Laila Saeed"
                        },
                        new
                        {
                            Id = new Guid("6ee4fba6-f091-448a-a69f-b430b99fac6d"),
                            Age = 21,
                            Grade = 97.78m,
                            Name = "Ali Mohamed"
                        },
                        new
                        {
                            Id = new Guid("6758b305-826c-4916-b0cf-55b88946624e"),
                            Age = 25,
                            Grade = 79.03m,
                            Name = "Hassan Ismail"
                        },
                        new
                        {
                            Id = new Guid("c13e4a9d-cdc6-4b65-840b-2ad5a651126e"),
                            Age = 25,
                            Grade = 88.4m,
                            Name = "Noor Ibrahim"
                        },
                        new
                        {
                            Id = new Guid("c6a0e4a8-54a4-4811-a226-d448841bc659"),
                            Age = 20,
                            Grade = 67.9m,
                            Name = "Noor Hussein"
                        },
                        new
                        {
                            Id = new Guid("086493f2-2e35-4feb-b83d-668b430fb388"),
                            Age = 19,
                            Grade = 97.69m,
                            Name = "Laila Salem"
                        },
                        new
                        {
                            Id = new Guid("c684afdb-d53f-4c4e-a792-da5a4554c493"),
                            Age = 25,
                            Grade = 92.64m,
                            Name = "Mona Nasser"
                        },
                        new
                        {
                            Id = new Guid("9890edac-6339-46ff-bb1e-3564d0609798"),
                            Age = 25,
                            Grade = 51.51m,
                            Name = "Noor Gad"
                        },
                        new
                        {
                            Id = new Guid("9f760151-730e-4066-9912-e0d79abfff15"),
                            Age = 23,
                            Grade = 65.24m,
                            Name = "Ahmed Nasser"
                        },
                        new
                        {
                            Id = new Guid("8e0e2e08-ce69-4961-97cf-28a8ce796520"),
                            Age = 25,
                            Grade = 80.31m,
                            Name = "Mona Salem"
                        },
                        new
                        {
                            Id = new Guid("33cb1c61-ce7c-4110-9f08-6875b1d2939d"),
                            Age = 20,
                            Grade = 69.96m,
                            Name = "Omar Salem"
                        },
                        new
                        {
                            Id = new Guid("14b82471-f7b5-4806-971d-503ef578e68e"),
                            Age = 22,
                            Grade = 90.3m,
                            Name = "Sara Tawfik"
                        },
                        new
                        {
                            Id = new Guid("11a4196c-096c-4be4-9cfa-cb5a941c0762"),
                            Age = 19,
                            Grade = 87.21m,
                            Name = "Ali Mohamed"
                        },
                        new
                        {
                            Id = new Guid("22474dab-1b95-433d-881a-9e47559bc5f3"),
                            Age = 19,
                            Grade = 85.57m,
                            Name = "Omar Salem"
                        },
                        new
                        {
                            Id = new Guid("e8093800-4772-43e4-b282-56cd1aa69520"),
                            Age = 22,
                            Grade = 72.8m,
                            Name = "Ahmed Salem"
                        },
                        new
                        {
                            Id = new Guid("2e6fc1c4-4bcb-4d4b-838e-be7464d3a4bd"),
                            Age = 20,
                            Grade = 77.2m,
                            Name = "Ahmed Ibrahim"
                        },
                        new
                        {
                            Id = new Guid("2296f4c2-64d3-4e1b-a2e3-d9cc25cc7045"),
                            Age = 20,
                            Grade = 68.06m,
                            Name = "Hassan Gad"
                        },
                        new
                        {
                            Id = new Guid("97ff82b0-1a8f-42b5-a3e4-703bf5e9815f"),
                            Age = 21,
                            Grade = 97.08m,
                            Name = "Youssef Gad"
                        },
                        new
                        {
                            Id = new Guid("919020c7-f058-4f82-aefa-597d269b7dc7"),
                            Age = 24,
                            Grade = 83.94m,
                            Name = "Noor Hussein"
                        },
                        new
                        {
                            Id = new Guid("7d53d4b6-1480-46ac-8748-356bc9f60830"),
                            Age = 18,
                            Grade = 58.71m,
                            Name = "Laila Ibrahim"
                        },
                        new
                        {
                            Id = new Guid("6b0bc1a6-4c48-4b29-bdd8-6f73bb69f949"),
                            Age = 21,
                            Grade = 91.41m,
                            Name = "Ali Saeed"
                        },
                        new
                        {
                            Id = new Guid("e2333d13-b75c-4a68-8636-dde57877d212"),
                            Age = 23,
                            Grade = 98.2m,
                            Name = "Laila Ismail"
                        },
                        new
                        {
                            Id = new Guid("f70ac03f-1d3e-46ae-80f2-119d811ec107"),
                            Age = 23,
                            Grade = 57.74m,
                            Name = "Youssef Mohamed"
                        },
                        new
                        {
                            Id = new Guid("728420a8-df81-4a8b-9298-994fdb958313"),
                            Age = 20,
                            Grade = 77.06m,
                            Name = "Khaled Gad"
                        },
                        new
                        {
                            Id = new Guid("0d87083b-e768-4733-a707-0de92413062d"),
                            Age = 25,
                            Grade = 67.19m,
                            Name = "Ali Salem"
                        },
                        new
                        {
                            Id = new Guid("abcb76d1-51df-458a-9c74-578681f0f9ea"),
                            Age = 22,
                            Grade = 62.94m,
                            Name = "Omar Fahmy"
                        },
                        new
                        {
                            Id = new Guid("7512b915-e2bb-4b51-af61-4ede72f892a3"),
                            Age = 19,
                            Grade = 50.33m,
                            Name = "Sara Ismail"
                        },
                        new
                        {
                            Id = new Guid("16d24042-a4ed-46fb-ada9-6b4343414fb5"),
                            Age = 19,
                            Grade = 89.76m,
                            Name = "Youssef Mohamed"
                        },
                        new
                        {
                            Id = new Guid("a767ed89-46f7-4cf9-a7fe-143f37f602e5"),
                            Age = 20,
                            Grade = 86.77m,
                            Name = "Ahmed Ismail"
                        },
                        new
                        {
                            Id = new Guid("ccb81913-1b99-4050-a565-5e9b6dd2754e"),
                            Age = 20,
                            Grade = 76.5m,
                            Name = "Ali Nasser"
                        },
                        new
                        {
                            Id = new Guid("ca66767f-62ab-46f6-8f12-831b182c3267"),
                            Age = 18,
                            Grade = 76.63m,
                            Name = "Sara Salem"
                        },
                        new
                        {
                            Id = new Guid("c8473a23-5285-4a0b-a703-a95505cc373f"),
                            Age = 22,
                            Grade = 78.01m,
                            Name = "Mona Mohamed"
                        },
                        new
                        {
                            Id = new Guid("4554745f-092a-4311-a451-475220a44f83"),
                            Age = 20,
                            Grade = 56.05m,
                            Name = "Khaled Ismail"
                        },
                        new
                        {
                            Id = new Guid("a0f2d56f-205d-423e-951b-b887a3db0682"),
                            Age = 21,
                            Grade = 78.86m,
                            Name = "Noor Nasser"
                        },
                        new
                        {
                            Id = new Guid("7fac6293-7dc8-4a3c-b8fe-9ecb042cfc51"),
                            Age = 22,
                            Grade = 86.81m,
                            Name = "Ali Ibrahim"
                        },
                        new
                        {
                            Id = new Guid("355da79f-daf2-413d-950d-53d4110539b3"),
                            Age = 22,
                            Grade = 73.93m,
                            Name = "Laila Tawfik"
                        },
                        new
                        {
                            Id = new Guid("06ea0a00-afa7-46a2-987a-03b3fe9bc81b"),
                            Age = 22,
                            Grade = 56.14m,
                            Name = "Ahmed Hussein"
                        },
                        new
                        {
                            Id = new Guid("2bb2a712-5467-4fe4-b215-6b6f99d06c5b"),
                            Age = 24,
                            Grade = 71.61m,
                            Name = "Youssef Nasser"
                        },
                        new
                        {
                            Id = new Guid("c2846923-e332-4ed1-8c52-75e4207c2247"),
                            Age = 24,
                            Grade = 62.72m,
                            Name = "Laila Tawfik"
                        },
                        new
                        {
                            Id = new Guid("999afa9d-7cc3-4aa7-ab2d-19520f30edc1"),
                            Age = 18,
                            Grade = 58.05m,
                            Name = "Ali Saeed"
                        },
                        new
                        {
                            Id = new Guid("de3a1215-e9b0-4f51-aca6-0e0837407269"),
                            Age = 25,
                            Grade = 98.92m,
                            Name = "Youssef Salem"
                        },
                        new
                        {
                            Id = new Guid("e25c2b36-e30f-4c74-a7b7-b7753fd6ecbf"),
                            Age = 22,
                            Grade = 86.23m,
                            Name = "Laila Nasser"
                        },
                        new
                        {
                            Id = new Guid("be741d8f-ef6a-4e9c-916b-402f9e39574f"),
                            Age = 25,
                            Grade = 73.42m,
                            Name = "Ahmed Ibrahim"
                        },
                        new
                        {
                            Id = new Guid("bdac6488-4e41-4aac-9769-c57d0bc9f215"),
                            Age = 24,
                            Grade = 63.61m,
                            Name = "Sara Mohamed"
                        },
                        new
                        {
                            Id = new Guid("c24033ce-1157-4dd4-a8ab-b2de5636446d"),
                            Age = 25,
                            Grade = 98.37m,
                            Name = "Mona Saeed"
                        },
                        new
                        {
                            Id = new Guid("3514c2fd-f667-4f05-a758-4b6f3c836000"),
                            Age = 24,
                            Grade = 74.81m,
                            Name = "Laila Salem"
                        },
                        new
                        {
                            Id = new Guid("e05e97a3-46a0-42a4-8b80-160fa15f2152"),
                            Age = 23,
                            Grade = 99.22m,
                            Name = "Youssef Mohamed"
                        },
                        new
                        {
                            Id = new Guid("b31eb6c4-9154-4144-a953-483adb11bda3"),
                            Age = 23,
                            Grade = 60.5m,
                            Name = "Youssef Gad"
                        },
                        new
                        {
                            Id = new Guid("188e8acb-fb3b-42b3-a7f4-e20d84bd4ea4"),
                            Age = 23,
                            Grade = 51.15m,
                            Name = "Ali Hussein"
                        },
                        new
                        {
                            Id = new Guid("bb184b99-3cdf-4043-ba42-6a0bf8255acf"),
                            Age = 24,
                            Grade = 73.57m,
                            Name = "Sara Ibrahim"
                        },
                        new
                        {
                            Id = new Guid("eaecde00-f222-47d0-9db1-21cbe1b424db"),
                            Age = 23,
                            Grade = 61.37m,
                            Name = "Omar Mohamed"
                        },
                        new
                        {
                            Id = new Guid("8dff5ba2-7608-462b-b6a7-03d7a1db266d"),
                            Age = 18,
                            Grade = 53.05m,
                            Name = "Omar Ibrahim"
                        },
                        new
                        {
                            Id = new Guid("6f77abc2-6afb-4d11-aba3-49fc66cf5060"),
                            Age = 24,
                            Grade = 78.19m,
                            Name = "Sara Nasser"
                        },
                        new
                        {
                            Id = new Guid("48e03ca0-e198-4f41-b6c4-152143906bc5"),
                            Age = 19,
                            Grade = 73.73m,
                            Name = "Khaled Saeed"
                        },
                        new
                        {
                            Id = new Guid("7b90d271-ae48-4492-9643-9536d50c07d6"),
                            Age = 19,
                            Grade = 90.59m,
                            Name = "Sara Saeed"
                        },
                        new
                        {
                            Id = new Guid("d9c8a064-2af2-4f9c-b193-51b864b5279a"),
                            Age = 24,
                            Grade = 63.95m,
                            Name = "Ahmed Gad"
                        },
                        new
                        {
                            Id = new Guid("610fbec5-638d-4a32-9e73-4b30044011a2"),
                            Age = 21,
                            Grade = 90.04m,
                            Name = "Khaled Salem"
                        },
                        new
                        {
                            Id = new Guid("aa54111a-ee76-4a70-a6d7-49fa1417c988"),
                            Age = 24,
                            Grade = 84.95m,
                            Name = "Omar Saeed"
                        },
                        new
                        {
                            Id = new Guid("1554a860-47fa-4aa8-b3a2-585f0c09239b"),
                            Age = 23,
                            Grade = 55.39m,
                            Name = "Ali Gad"
                        },
                        new
                        {
                            Id = new Guid("8868a7bd-f5a4-4b4b-a92a-b591e847ca11"),
                            Age = 18,
                            Grade = 64.8m,
                            Name = "Youssef Nasser"
                        },
                        new
                        {
                            Id = new Guid("ff93dd74-4ccc-49b1-9e43-985c5b3b482a"),
                            Age = 23,
                            Grade = 57.46m,
                            Name = "Ahmed Mohamed"
                        },
                        new
                        {
                            Id = new Guid("3c9cd972-33f5-4355-987f-f144d63068f0"),
                            Age = 19,
                            Grade = 81.79m,
                            Name = "Ali Fahmy"
                        },
                        new
                        {
                            Id = new Guid("a4062d45-eb9e-49d8-ac6f-c6e1de7ce056"),
                            Age = 25,
                            Grade = 54.5m,
                            Name = "Ali Salem"
                        },
                        new
                        {
                            Id = new Guid("7dc192c9-ddc7-4f8f-94d9-073277ed9a00"),
                            Age = 21,
                            Grade = 52.56m,
                            Name = "Omar Ismail"
                        },
                        new
                        {
                            Id = new Guid("d8332380-f3ab-4577-bead-09c064b7450f"),
                            Age = 18,
                            Grade = 58.48m,
                            Name = "Laila Fahmy"
                        },
                        new
                        {
                            Id = new Guid("3a8bbe3e-bff8-4ebd-98c7-3a891c1e6b19"),
                            Age = 21,
                            Grade = 96.74m,
                            Name = "Hassan Fahmy"
                        },
                        new
                        {
                            Id = new Guid("4ea99ace-c5a2-4ca3-b748-0094a40d8207"),
                            Age = 23,
                            Grade = 99.86m,
                            Name = "Mona Fahmy"
                        },
                        new
                        {
                            Id = new Guid("e3f1681c-5620-4844-b7bb-e847497afee1"),
                            Age = 19,
                            Grade = 77.94m,
                            Name = "Mona Mohamed"
                        },
                        new
                        {
                            Id = new Guid("dbb24c43-3457-4571-8077-1eabb750609d"),
                            Age = 21,
                            Grade = 54.37m,
                            Name = "Ali Hussein"
                        },
                        new
                        {
                            Id = new Guid("529ce3a5-5838-4924-9ff7-4720acf47e01"),
                            Age = 18,
                            Grade = 83.0m,
                            Name = "Omar Ismail"
                        },
                        new
                        {
                            Id = new Guid("701fa799-6714-4b43-ad72-852e4f0d43d6"),
                            Age = 19,
                            Grade = 87.03m,
                            Name = "Omar Mohamed"
                        },
                        new
                        {
                            Id = new Guid("d3dbb944-8550-4ec1-93b7-64e668b0cff9"),
                            Age = 20,
                            Grade = 82.66m,
                            Name = "Omar Tawfik"
                        },
                        new
                        {
                            Id = new Guid("ff12401c-9f10-4fcb-b9a9-789f228e8bbd"),
                            Age = 18,
                            Grade = 91.18m,
                            Name = "Ali Gad"
                        },
                        new
                        {
                            Id = new Guid("043cb9e0-7a65-45ac-85aa-126d09eb3db7"),
                            Age = 18,
                            Grade = 65.97m,
                            Name = "Noor Nasser"
                        },
                        new
                        {
                            Id = new Guid("a5c0a046-ad07-4d80-8d3e-7a46618f2fe3"),
                            Age = 21,
                            Grade = 59.81m,
                            Name = "Omar Mohamed"
                        },
                        new
                        {
                            Id = new Guid("86a85e62-a030-4156-85df-07920149318e"),
                            Age = 18,
                            Grade = 56.74m,
                            Name = "Sara Ismail"
                        },
                        new
                        {
                            Id = new Guid("e9334d1f-2c67-4b3e-a231-e59a0be4b583"),
                            Age = 20,
                            Grade = 78.45m,
                            Name = "Ahmed Salem"
                        },
                        new
                        {
                            Id = new Guid("ade9efeb-c5e7-4171-ab6d-9c4253f6db40"),
                            Age = 24,
                            Grade = 64.51m,
                            Name = "Youssef Saeed"
                        },
                        new
                        {
                            Id = new Guid("a5465482-948a-48a0-aa08-59b649db1d9f"),
                            Age = 19,
                            Grade = 91.62m,
                            Name = "Youssef Ibrahim"
                        },
                        new
                        {
                            Id = new Guid("d69e2796-cdb4-4f9f-b549-a54800df7208"),
                            Age = 22,
                            Grade = 54.34m,
                            Name = "Ahmed Saeed"
                        },
                        new
                        {
                            Id = new Guid("440e42fc-1a1d-4b65-8358-169bb1c71dd5"),
                            Age = 19,
                            Grade = 83.53m,
                            Name = "Ali Ismail"
                        },
                        new
                        {
                            Id = new Guid("5a01d982-0586-431b-aea5-c58bbbc89aa5"),
                            Age = 19,
                            Grade = 52.88m,
                            Name = "Hassan Salem"
                        },
                        new
                        {
                            Id = new Guid("7fb1c3a0-446d-4932-b044-b5571b2bb99b"),
                            Age = 21,
                            Grade = 93.39m,
                            Name = "Sara Mohamed"
                        },
                        new
                        {
                            Id = new Guid("13a32ac1-16da-42bf-9a5c-2dff0a53a479"),
                            Age = 22,
                            Grade = 60.22m,
                            Name = "Youssef Fahmy"
                        },
                        new
                        {
                            Id = new Guid("cfed1125-6568-48ee-89d0-e0cd762f32cf"),
                            Age = 23,
                            Grade = 56.0m,
                            Name = "Youssef Salem"
                        },
                        new
                        {
                            Id = new Guid("82f6664f-8cc9-483f-abb2-701f904655a8"),
                            Age = 25,
                            Grade = 64.48m,
                            Name = "Hassan Mohamed"
                        },
                        new
                        {
                            Id = new Guid("73736082-e04d-400e-9e33-cd4581284ae5"),
                            Age = 24,
                            Grade = 62.46m,
                            Name = "Youssef Salem"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
